#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom dplyr bind_rows
#' @importFrom dplyr filter
#' @importFrom EBImage gblur
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 aes_string
#' @importFrom ggplot2 coord_equal
#' @importFrom ggplot2 geom_histogram
#' @importFrom ggplot2 geom_tile
#' @importFrom ggplot2 geom_vline
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 scale_color_viridis_c
#' @importFrom ggplot2 theme_classic
#' @importFrom ggplot2 theme_light
#' @importFrom patchwork plot_annotation
#' @importFrom patchwork wrap_plots
#' @importFrom rlang .data
#' @importFrom sf st_area
#' @importFrom sf st_as_sf
#' @importFrom sf st_boundary
#' @importFrom sf st_cast
#' @importFrom sf st_convex_hull
#' @importFrom sf st_coordinates
#' @importFrom sf st_geometry
#' @importFrom sf st_intersects
#' @importFrom sf st_is_empty
#' @importFrom sf st_length
#' @importFrom sf st_make_valid
#' @importFrom sf st_minimum_rotated_rectangle
#' @importFrom sf st_sfc
#' @importFrom sf st_union
#' @importFrom smoothr smooth
#' @importFrom SpatialExperiment spatialCoords
#' @importFrom spatstat.explore bw.diggle
#' @importFrom spatstat.explore density.ppp
#' @importFrom spatstat.geom as.rectangle
#' @importFrom spatstat.geom grow.rectangle
#' @importFrom spatstat.geom marks
#' @importFrom spatstat.geom owin
#' @importFrom spatstat.geom setmarks
#' @importFrom spatstat.geom subset.ppp
#' @importFrom spatstat.geom superimpose
#' @importFrom spatstat.random rpoispp
#' @importFrom stats density
#' @importFrom stats runif
#' @importFrom SummarizedExperiment assays
#' @importFrom SummarizedExperiment colData
#' @importFrom terra ext
#' @importFrom terra set.ext
#' @importFrom terra xmax
#' @importFrom terra xmin
#' @importFrom terra ymax
#' @importFrom terra ymin
## usethis namespace: end
NULL
